name: Test with Tags

on:
  workflow_dispatch:
    inputs:
      include_tags:
        description: 'Comma-separated list of tags to include (e.g., Fast,IntegrationTest)'
        required: false
        default: ''
      exclude_tags:
        description: 'Comma-separated list of tags to exclude (e.g., Slow,DatabaseTest)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'graalvm'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Run tests with specified tags
      run: |
        GRADLE_COMMAND="./gradlew test"
        if [ -n "${{ github.event.inputs.include_tags }}" ]; then
          GRADLE_COMMAND="$GRADLE_COMMAND -PincludeTags=${{ github.event.inputs.include_tags }}"
        fi
        if [ -n "${{ github.event.inputs.exclude_tags }}" ]; then
          GRADLE_COMMAND="$GRADLE_COMMAND -PexcludeTags=${{ github.event.inputs.exclude_tags }}"
        fi
        echo "Running: $GRADLE_COMMAND"
        $GRADLE_COMMAND
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: build/reports/tests/